{
  "_id": {
    "$oid": "6071ba1e43dd71267de10db6"
  },
  "author_association": "MEMBER",
  "issue_url": "https://api.github.com/repos/assetgraph/assetgraph/issues/869",
  "updated_at": "2018-06-01T14:04:53Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/assetgraph/assetgraph/pull/869#issuecomment-393890947",
  "created_at": "2018-06-01T14:04:53Z",
  "id": 393890947,
  "body": "I don't understand this linting error. On my machine the linter passes with no problems",
  "user": {
    "gists_url": "https://api.github.com/users/Munter/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/Munter/repos",
    "following_url": "https://api.github.com/users/Munter/following{/other_user}",
    "starred_url": "https://api.github.com/users/Munter/starred{/owner}{/repo}",
    "login": "Munter",
    "followers_url": "https://api.github.com/users/Munter/followers",
    "type": "User",
    "url": "https://api.github.com/users/Munter",
    "subscriptions_url": "https://api.github.com/users/Munter/subscriptions",
    "received_events_url": "https://api.github.com/users/Munter/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/331790?v=4",
    "events_url": "https://api.github.com/users/Munter/events{/privacy}",
    "html_url": "https://github.com/Munter",
    "site_admin": false,
    "id": 331790,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjMzMTc5MA==",
    "organizations_url": "https://api.github.com/users/Munter/orgs"
  },
  "url": "https://api.github.com/repos/assetgraph/assetgraph/issues/comments/393890947",
  "node_id": "MDEyOklzc3VlQ29tbWVudDM5Mzg5MDk0Nw=="
}