{
  "_id": {
    "$oid": "60720d1443dd71267de27f4f"
  },
  "author_association": "MEMBER",
  "issue_url": "https://api.github.com/repos/python-trio/trio/issues/687",
  "updated_at": "2018-09-27T22:45:19Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/python-trio/trio/pull/687#issuecomment-425265967",
  "created_at": "2018-09-27T22:45:19Z",
  "id": 425265967,
  "body": "Yeah, the coverage is claiming that our IPython-related tests aren't running at all in this PR. Weird.",
  "user": {
    "gists_url": "https://api.github.com/users/njsmith/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/njsmith/repos",
    "following_url": "https://api.github.com/users/njsmith/following{/other_user}",
    "starred_url": "https://api.github.com/users/njsmith/starred{/owner}{/repo}",
    "login": "njsmith",
    "followers_url": "https://api.github.com/users/njsmith/followers",
    "type": "User",
    "url": "https://api.github.com/users/njsmith",
    "subscriptions_url": "https://api.github.com/users/njsmith/subscriptions",
    "received_events_url": "https://api.github.com/users/njsmith/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/609896?v=4",
    "events_url": "https://api.github.com/users/njsmith/events{/privacy}",
    "html_url": "https://github.com/njsmith",
    "site_admin": false,
    "id": 609896,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjYwOTg5Ng==",
    "organizations_url": "https://api.github.com/users/njsmith/orgs"
  },
  "url": "https://api.github.com/repos/python-trio/trio/issues/comments/425265967",
  "node_id": "MDEyOklzc3VlQ29tbWVudDQyNTI2NTk2Nw=="
}