{
  "_id": {
    "$oid": "60727f3043dd71267de53956"
  },
  "author_association": "NONE",
  "issue_url": "https://api.github.com/repos/vercel/next.js/issues/21679",
  "updated_at": "2021-01-30T09:17:02Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/vercel/next.js/issues/21679#issuecomment-770182480",
  "created_at": "2021-01-30T09:17:02Z",
  "id": 770182480,
  "body": "...but the problem is with `next`, not `next-pwa`. I'm getting the same error after upgrading to `next@10.0.6` and `next-pwa` is not in my dependencies.",
  "user": {
    "gists_url": "https://api.github.com/users/icflorescu/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/icflorescu/repos",
    "following_url": "https://api.github.com/users/icflorescu/following{/other_user}",
    "starred_url": "https://api.github.com/users/icflorescu/starred{/owner}{/repo}",
    "login": "icflorescu",
    "followers_url": "https://api.github.com/users/icflorescu/followers",
    "type": "User",
    "url": "https://api.github.com/users/icflorescu",
    "subscriptions_url": "https://api.github.com/users/icflorescu/subscriptions",
    "received_events_url": "https://api.github.com/users/icflorescu/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/581999?v=4",
    "events_url": "https://api.github.com/users/icflorescu/events{/privacy}",
    "html_url": "https://github.com/icflorescu",
    "site_admin": false,
    "id": 581999,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjU4MTk5OQ==",
    "organizations_url": "https://api.github.com/users/icflorescu/orgs"
  },
  "url": "https://api.github.com/repos/vercel/next.js/issues/comments/770182480",
  "node_id": "MDEyOklzc3VlQ29tbWVudDc3MDE4MjQ4MA=="
}